export type Language = {
    title: string,
    navHome: string,
    navDashboard: string,
    date: string,
    systolicPressure: string,
    diastolicPressure: string,
    heartRate: string,
    bloodSugarLevel: string,
    bloodSugarUnit: string,
    buttonSubmit: string,
    buttonCancel: string,
    buttonOK: string,
    update: string,
    delete: string,
    showMore: string,
    showLess: string,
    deleteConfirmation: string,
    timeAt: string,
    yearSelection: string
};

export const english: Language = {
    title: 'heart monitor app',
    navHome: 'home',
    navDashboard: 'dashboard',
    date: 'date',
    systolicPressure: 'systolic pressure',
    diastolicPressure: 'diastolic pressure',
    heartRate: 'heart rate',
    bloodSugarLevel: 'blood sugar level',
    bloodSugarUnit: 'blood sugar level unit',
    buttonSubmit: 'submit',
    buttonCancel: 'cancel',
    buttonOK: 'OK',
    update: 'update',
    delete: 'delete',
    showMore: 'show more',
    showLess: 'show less',
    deleteConfirmation: 'Do you want to delete the data entry for',
    timeAt: 'at',
    yearSelection: 'Select a year'
};

export const tiếng_việt: Language = {
    title: 'ứng dụng theo dõi tim mạch',
    navHome: 'trang chủ',
    navDashboard: 'bảng dữ liệu',
    date: 'ngày',
    systolicPressure: 'tâm thu',
    diastolicPressure: 'tâm trương',
    heartRate: 'nhịp tim',
    bloodSugarLevel: 'đường huyết',
    bloodSugarUnit: 'đơn vị đường huyết',
    buttonSubmit: 'nhập',
    buttonCancel: 'hủy',
    buttonOK: 'đồng ý',
    update: 'sửa',
    delete: 'xóa',
    showMore: 'xem thêm',
    showLess: 'thu lại',
    deleteConfirmation: 'Bạn có muốn xóa dữ liệu cho ngày',
    timeAt: 'lúc',
    yearSelection: 'Chọn năm'
};