export const english = {
    title: 'heart monitor app',
    navHome: 'home',
    navDashboard: 'dashboard',
    date: 'date',
    systolicPressure: 'systolic pressure',
    diastolicPressure: 'diastolic pressure',
    heartRate: 'heart rate',
    bloodSugarLevel: 'blood sugar level',
    bloodSugarUnit: 'blood sugar level unit',
    buttonSubmit: 'submit',
    buttonCancel: 'cancel',
    buttonOK: 'OK',
    update: 'update',
    delete: 'delete',
    showMore: 'show more',
    showLess: 'show less',
    deleteConfirmation: 'Do you want to delete the data entry for',
    timeAt: 'at'
};

export const tiếng_việt = {
    title: 'ứng dụng theo dõi tim mạch',
    navHome: 'trang chủ',
    navDashboard: 'bảng dữ liệu',
    date: 'ngày',
    systolicPressure: 'huyết áp tâm thu',
    diastolicPressure: 'huyết áp tâm trương',
    heartRate: 'nhịp tim',
    bloodSugarLevel: 'đường huyết',
    bloodSugarUnit: 'đơn vị đường huyết',
    buttonSubmit: 'nhập',
    buttonCancel: 'hủy',
    buttonOK: 'đồng ý',
    update: 'sửa',
    delete: 'xóa',
    showMore: 'xem thêm',
    showLess: 'thu lại',
    deleteConfirmation: 'Bạn có muốn xóa dữ liệu cho ngày',
    timeAt: 'lúc'
};